version: '3'
services:
   python3_cron:
     build:
       context: .
       args:
         UID: $UID
         GID: $GID
     container_name: 'python3_cron'
     working_dir: '/opt/LR'
     tty: true
     volumes:
        - ./LR:/opt/LR
